/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export interface Purchasequote {
  maximum: number;
  minimum: number;
  senderName: string;
  senderPhone: string;
  senderWallet: string;
  timestamp: Int8;
  token: string;
  usdPriceInSle: number;
}

export interface DB {
  purchasequote: Purchasequote;
}
