/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export interface Purchasequote {
  id: Generated<number>;
  maximum: number;
  minimum: number;
  senderName: string;
  senderPhone: string;
  senderWallet: string;
  timestamp: Int8;
  token: string;
  usdPriceInSle: number;
}

export interface DB {
  purchasequote: Purchasequote;
}
